In [1]:
import pandas as pd

In [2]:
RANDOM_STATE = 13
fraction = 1

input_file_path_1 = "/Users/kaengreg/Documents/Работа /НИВЦ/ispras/data/countries_classification/train_raw.jsonl"
input_file_path_2 = "/Users/kaengreg/Documents/Работа /НИВЦ/ispras/data/toxicity_classification/ru_social_tox_stance_26_04_train.jsonl"
output_file_path = "/Users/kaengreg/Documents/Работа /НИВЦ/ispras/data/toxicity_classification/train_mixed_stance_tox.jsonl"

In [3]:
def data_read(path: str) -> pd.DataFrame:
    return pd.read_json(path, lines=True)

train_data = data_read(input_file_path_1)
train_data

,sentence_id,text,target,stance
0,10137,"Обвинения Украины в том, что она готовится при...",Россия,NEU
1,20700,Швейцарские финансовые учреждения активно подд...,Россия,PRO
2,19879,Россия неоднократно отправила официальные дипл...,Россия,PRO
3,1581,Совет Баренцева/Евроарктического региона приос...,Россия,NEU
4,26683,2 августа 2019 года Россия отметила внимание с...,Россия,PRO
...,...,...,...,...
21883,5090,11 октября в газете «Коммерсантъ» была опублик...,Россия,NEU
21884,11127,В 2016 году по инициативе Верховного суда РФ б...,Россия,NEU
21885,25576,В начале 1999 года заместитель генерального пр...,Россия,PRO
21886,8032,По данным американского Института изучения вой...,Россия,ANTI
21887,25827,В рамках межгосударственных переговоров Грузия...,Россия,PRO

In [4]:
refined_train = train_data.sample(frac=fraction, random_state=RANDOM_STATE)
refined_train

,sentence_id,text,target,stance
17153,6136,"Также снизилась доля граждан Украины, слушающи...",Россия,NEU
10255,14808,"Россия новую власть не признала, до новых выбо...",Россия,NEU
3129,19770,Премьер-министр Великобритании Риши Сунак отме...,Россия,PRO
3041,7509,Россия также нарушила статью 51 Гаагской конве...,Россия,ANTI
3604,23873,В публикации на сайте уважаемой канадской газе...,Россия,PRO
...,...,...,...,...
153,10195,"Издание SOTA пришло к выводу, что он является ...",Россия,NEU
866,6515,"7 июня министр обороны Шойгу заявил, что всего...",Россия,NEU
74,16969,В 1995 году Владимир Путин успешно руководил р...,Россия,PRO
14512,2449,По мнению Кацпера Рекавека из Университета Осл...,Россия,ANTI
338,6508,В середине августа главнокомандующий ВСУ Валер...,Россия,ANTI

In [5]:
train_data_addition = data_read(input_file_path_2)
train_data_addition

,sentence_id,text,target,toxicity_label,stance
0,0,"[id2958984|Александр], Жиды и бандеровцы тем и...",Россия,TOX,ANTI
1,1,Декларация 3-НДФЛ с гарантией от 500 рублей. У...,Россия,NEU,NEU
2,2,Тогда придется писать так: Ростелеком (террори...,Россия,TOX,ANTI
3,3,Не фиг было Путину заниматься декомунизацией в...,Россия,NEU,ANTI
4,4,"Там правящий блок партий, как в той же РФ или ...",Россия,TOX,NEU
...,...,...,...,...,...
8448,8448,Нет чтобы выложить б/у рельсами на века и забы...,Россия,NEU,NEU
8449,8449,"Есть ли основание, в обвинении по статье УК РФ?",Россия,NEU,NEU
8450,8450,я когда вижу кадры как памятники ленину или ещ...,Россия,NEU,NEU
8451,8451,Вывод по Грузии просто великолепен. Дрессирова...,Россия,TOX,ANTI
8452,8452,Мы решим проблему с предоставлением займа/кред...,Россия,NEU,NEU

In [6]:
refined_train = pd.concat([refined_train, train_data_addition], ignore_index=True)
refined_train

,sentence_id,text,target,stance,toxicity_label
0,6136,"Также снизилась доля граждан Украины, слушающи...",Россия,NEU,NaN
1,14808,"Россия новую власть не признала, до новых выбо...",Россия,NEU,NaN
2,19770,Премьер-министр Великобритании Риши Сунак отме...,Россия,PRO,NaN
3,7509,Россия также нарушила статью 51 Гаагской конве...,Россия,ANTI,NaN
4,23873,В публикации на сайте уважаемой канадской газе...,Россия,PRO,NaN
...,...,...,...,...,...
30336,8448,Нет чтобы выложить б/у рельсами на века и забы...,Россия,NEU,NEU
30337,8449,"Есть ли основание, в обвинении по статье УК РФ?",Россия,NEU,NEU
30338,8450,я когда вижу кадры как памятники ленину или ещ...,Россия,NEU,NEU
30339,8451,Вывод по Грузии просто великолепен. Дрессирова...,Россия,ANTI,TOX
30340,8452,Мы решим проблему с предоставлением займа/кред...,Россия,NEU,NEU

In [7]:
refined_train = refined_train.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
refined_train = refined_train.fillna(value={"toxicity_label":"UNDEF"})
refined_train

,sentence_id,text,target,stance,toxicity_label
0,16922,"Отец Владимира Путина, Владимир Спиридонович, ...",Россия,NEU,UNDEF
1,3381,В ходе полномасштабного вторжения в Украину ро...,Россия,ANTI,UNDEF
2,3709,"интересно, а если бы в россии так бахнуло, кто...",Россия,NEU,NEU
3,5929,"Максим замечательный, но говорит очень странны...",Россия,NEU,TOX
4,20757,Россия продолжает активное участие в проектах ...,Россия,PRO,UNDEF
...,...,...,...,...,...
30336,5478,в советском союзе каждый третий владел прочным...,СССР,PRO,NEU
30337,2192,"[id18343077|Wassily], сразу видно Кто скакал и...",Россия,NEU,NEU
30338,15260,Президент Российской Федерации В. В. Путин в о...,Россия,NEU,UNDEF
30339,18521,"Россия решительно защитила свою позицию, заяви...",Россия,PRO,UNDEF
30340,3155,25 октября 2024 года The Washington Post сообщ...,Россия,NEU,UNDEF

In [8]:
refined_train.to_json(output_file_path, orient="records", lines=True, force_ascii=False)
print(f"Saved {len(refined_train)} rows to {output_file_path}")

Saved 30341 rows to /Users/kaengreg/Documents/Работа /НИВЦ/ispras/data/toxicity_classification/train_mixed_stance_tox.jsonl